version: "3.7"

services:
  database_users:
    image: bitnami/postgresql:latest
    container_name: db_users
    build: 
      context: .
      dockerfile: pg-Dockerfile
      network: host
    environment: 
      - POSTGRES_DATABASE=user_db
      - POSTGRESQL_USERNAME=user_store
      - POSTGRES_PASSWORD=store
      - POSTGRESQL_POSTGRES_PASSWORD=admin_pass
      - POSTGRESQL_POSTGRES_USERNAME=postgres
      - POSTGRESQL_PORT_NUMBER=5432
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

  app:
    build: .
    depends_on:
      - database_users
    container_name: app_users
    volumes:
      - .:/usr/app
    network_mode: "host"

volumes:
  postgresql_data:
    driver: local
