version: '3.7'

services:
  database_candys:
    image: bitnami/postgresql:latest
    container_name: db_candys
    build: 
      context: .
      dockerfile: pg-Dockerfile
      network: host
    environment: 
      - POSTGRES_DATABASE=candy_db
      - POSTGRESQL_USERNAME=candy_user
      - POSTGRES_PASSWORD=candy
      - POSTGRESQL_POSTGRES_PASSWORD=admin_pass
      - POSTGRESQL_POSTGRES_USERNAME=postgres
      - POSTGRESQL_PORT_NUMBER=5434
    ports:
      - "5434:5434"
    volumes:
      - postgresql_data:/bitnami/postgresql

  app:
    build: .
    depends_on:
      - database_candys
    container_name: app_candys
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  postgresql_data:
    driver: local
